{
 "title": "Observability Sandbox",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_heap_bytes{instance=\"api:8080\",service=\"API\"}"
    }
   ]
  },
  {
   "title": "'/greet' Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_greet_request_duration_seconds_sum[1m])) / sum(rate(api_greet_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "API Output",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service=\"api\"}"
    }
   ]
  }
 ]
}